services:

  api:
    build: .
    container_name: devtaskops-api

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: postgresql://devops:devops@postgres:5432/devtaskops?schema=public
      PORT: 3000

    depends_on:
      - postgres

    volumes:
      - .:/app
      - /app/node_modules

    command: npm run dev

  postgres:
    image: postgres:16
    container_name: devtaskops-postgres

    restart: always

    environment:
      POSTGRES_DB: devtaskops
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: devtaskops-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - api
  
  grafana:
    image: grafana/grafana
    container_name: devtaskops-grafana

    ports:
      - "3001:3000"

    depends_on:
      - prometheus

volumes:
  postgres_data: